name: fluentd-operator
version: 0.0.2
appVersion: 0.3.1
description: Distribution of Fluentd as K8S daemonset
keywords:
- fluentd
- operator
home: https://github.com/vmware/kube-fluentd-operator
sources:
- https://github.com/vmware/kube-fluentd-operator
maintainers:
- name: sylus
  email: william.hearn@canada.ca
- name: Zachary Seguin
  email: zachary.seguin@canada.ca
engine: gotpl
